### ISSUE TITLE
I am not convinced that it is viable to enumerate all possible melodies

### ISSUE THREAD

**Issue by chalkwalk** [allthemusicllc/atm-cli#11]
While I like the concept of being able to generate all possible melodies I think this is mathematically implausible. I will try to illustrate my point with specific numerical values. Note that where rounding occurs I round down (favouring this being a possible endeavour). Similarly I make some assumptions which tend to err on the side of shrinking the space and not growing it.

Assuming playing around a different key centre is equivalent we can divide the number of possible notes by 12. Let's assume only the keys on a piano keyboard (there exists other pitches) so we could call it 88/12 choices per a note (rounded down to 7). We ignore tempo, and swing, but similarly rhythm is part of a melody. Let's say we allow note lengths from 1/1 to 1/32 and triplets (12 options). We also care about rests; let's say we also have those 12 options for length, plus 0 length (no gap), i.e 13 possibilities. One could say that you have 12 notes and 11 (potentially absent) rests in the phrase, so we have:
7^12 * 12^12 * 13^11 = 2.21 * 10^35
We could reasonably say that a melody could be encoded in this way at several (<12) different time divisions (since we don't care about tempo) so we can divide the number by 12 to eliminate that form of redundancy:
2.21 * 10^35 / 12 = 1.84 * 10^34
In the best possible case you need enough bits to index into that list to encode a melody (densest possible encoding) meaning the base 2 logarithm of that number worth of bits:
ln(1.84 * 10^34) / ln(2) = 113.8 bits
Let's convert that to bytes then round it down: 14 bytes per melody... so to store all optimally encoded melodies we need:
1.84 * 10^34 * 14 bytes = 2.5 * 10^35 bytes = 2.5 * 10^11 yottabytes
This is many orders of magnitude more than the total amount of data storage in the world. In short, I do not believe it is possible to copyright (encode and store in persistent tangible media) every possible 12 note melody built in the western European musical tradition, nor will it ever be.

**Comment by fdenzer** [comment]
The (official?) talk on allthemusic does not do math
https://www.youtube.com/embed/sJtm0MoOgiU

Many websites do, though. 
https://plus.maths.org/content/how-many-melodies-are-there
comes up with ca. 8.25 E 19

**Comment by allthemusicllc** [comment]
@chalkwalk we take your point that if you take into account all possible values for rhythm, the set of melodies is very large. However, the set is still countable (finite), and many (most) of those melodies are not audibly pleasing. Moreover, we predict that advances in computing and clever storage mechanisms (plus some code improvements) may incrementally increase the largest set of melodies one could generate.

For our first dataset, we aimed to generate a large majority of common melodies that have been used in popular music for centuries, which we believe we did. We look forward to working with others to expand on our initial work, generate more datasets, and make content more accessible to non-technical people!

**Comment by alex-che** [comment]
Actual numbers depends on the definition of "melody" and what makes two melodies different.
If we consider an average human listener and an average popular western song, we probably can make several simplifications.
1. Melody is written in some major or minor tonality.
2. Transposing a melody does not make it different.
3. Melodies, which differs only by tempo, are the same.
4. Some combinations of note lengths may be considered the same: e.g. two 1/2 'Do' in a row are the same as one 1/1 'Do'.
5. Rests may be replaced by prolonging the note by corresponding length: e.g. 1/2 'Do' and then 1/2 rest is the same as 1/1 'Do'.
6. 12 beats are enough for melody length.

Points 1-2 leaves us with only 8 notes needed (3 bits per note).
Points 3-6 leaves us with only 12 note placeholders.
It makes 8^12=~7E10 different melodies, 3*12=36 bits per melody.
Or 36 * 8^12 bits = 288 GB for all the melodies.

Whether the simplifications above are valid is discussable, but at the end if depends what we actually want to achieve.

**Comment by chalkwalk** [comment]
I would definitely argue that a pair of consecutive notes of the same pitch don't correspond to the same melody, consider the classic "happy birthday" without the repeated notes and ask yourself if it's the same melody. Similarly for rests, a melody that is 1/2 beat vs one that is a 1/32nd beat every 1/2 beat (with rests) will be very distinct on most instruments. Similarly, 1 octave doesn't allow certain resolutions like enclosures to the root.

I agree that in practise only a subset of the melodies are what one might consider "musical" but then we are in a more difficult situation: complete enumeration of a parameter space is trivial, restricting to 'musical' options is far more difficult and subjective. Does my phrase have to end on the root? Can I play a b3 in a major key? What about a b5 is minor? natural 7 in mixolydian? Are they okay as a passing tones? what about chromatic motions in general? Notes borrowed from relative modes? Tones from a tritone substitution? Notes from a negative harmonic equivalent of a diatonic 7th?

My general point in this issue is that for complete coverage (even allowing for equivalence due to key change and beat division) there is an entirely impractical amount of storage required: even accounting doubling storage density every six months (extremely optimistic and not realistic) we woudn't have enough storage on the entire planet for 30 years. If you can genuinely codify all the rules of music then you can cull that space tremendously, but even a trillion times cull leaves us with tens of zettabytes of storage required: still likely impractical for 20 years.
