### ISSUE TITLE
Link in README returns access denied

### ISSUE THREAD

**Issue by deanputney** [allthemusicllc/atm-cli#13]
The link in the README to download a set of samples at the end of the Getting Started section is read-protected. For this to be useful the file should be publicly available for download.

The specific link is:
https://allthemusic.s3.amazonaws.com/datasets/20190727.C4_D4_E4_F4_G4_A4_B4_C5.L10.tar

**Comment by allthemusicllc** [comment]
Fixed in #20, thank you for letting us know! Please open another issue if you have trouble downloading datasets from the updated link in the README.

**Comment by deanputney** [comment]
You might consider closing these issues after the PR is merged. From what a visitor might see now on the project homepage this bug still appears open. Thanks for addressing!
