### ISSUE TITLE
Running fails with error "on an `Err` value: ()'"

### ISSUE THREAD

**Issue by nailz420** [allthemusicllc/atm-cli#15]
[error.log](https://github.com/allthemusicllc/atm-cli/files/4253201/error.log)

Followed all the instructions to compile and run. Every combination of example parameters fails with the attached error. Tried on 2 different machines. Any ideas?

**Comment by nailz420** [comment]
Apparently it's a windows console thing. It runs in cygwin console and I assume it will run fine in linux/WLS.

**Comment by allthemusicllc** [comment]
Thanks for following up @nailz420, let us know if you encounter any other issues!
