### ISSUE TITLE
File permissions inside tar archives are all zero

### ISSUE THREAD

**Issue by hselasky** [allthemusicllc/atm-cli#16]
Hi,

When extracting the tar archives the permissions are all zero. This is a problem when opening the files.

tar --list -vf test.mid | less
----------  0 0      0         398 Jan  1  1970 6060/6060/batch1.tar.gz
----------  0 0      0         407 Jan  1  1970 6060/6060/batch2.tar.gz
----------  0 0      0         408 Jan  1  1970 6060/6060/batch3.tar.gz
----------  0 0      0         406 Jan  1  1970 6060/6060/batch4.tar.gz
----------  0 0      0         408 Jan  1  1970 6060/6060/batch5.tar.gz
----------  0 0      0         411 Jan  1  1970 6060/6060/batch6.tar.gz
----------  0 0      0         409 Jan  1  1970 6060/6060/batch7.tar.gz
----------  0 0      0         407 Jan  1  1970 6060/6060/batch8.tar.gz
----------  0 0      0         412 Jan  1  1970 6060/6060/batch9.tar.gz
----------  0 0      0         417 Jan  1  1970 6060/6060/batch10.tar.gz
----------  0 0      0         406 Jan  1  1970 6060/6060/batch11.tar.gz

Could you set "rw" at least?

--HPS

**Comment by allthemusicllc** [comment]
@hselasky this should be fixed now, and we've added additional storage backends. Take a look at https://github.com/allthemusicllc/atm-cli/blob/master/src/storage/tar_archive.rs#L102.  Please let us know if the issue persists, and thanks for reporting this!

**Comment by hselasky** [comment]
Thank you!
