### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by MaciejTest** [allthemusicllc/atm-cli#17]
atm single -n 'C:4,D:4,E:4,F:4,G:4,A:4,B:4,C:5' -t test.mid
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', src\libcore\result.rs:1188:5
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\sys_common\backtrace.rs:84
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\sys_common\backtrace.rs:61
   3: core::fmt::write
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libcore\fmt\mod.rs:1025
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\io\mod.rs:1426
   5: std::sys_common::backtrace::_print
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\sys_common\backtrace.rs:65
   6: std::sys_common::backtrace::print
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\sys_common\backtrace.rs:50
   7: std::panicking::default_hook::{{closure}}
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:193
   8: std::panicking::default_hook
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:210
   9: std::panicking::rust_panic_with_hook
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:471
  10: std::panicking::begin_panic_handler
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:375
  11: core::panicking::panic_fmt
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libcore\panicking.rs:84
  12: core::result::unwrap_failed
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libcore\result.rs:1188
  13: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  14: <libatm::MIDINoteSequence as core::str::FromStr>::from_str
  15: atm::directives::parse_sequence_argument
  16: <atm::directives::SingleDirectiveArgs as core::convert::From<&clap::args::arg_matches::ArgMatches>>::from
  17: atm::cli::Cli::run
  18: core::ptr::real_drop_in_place
  19: vtable
  20: std::rt::lang_start_internal::{{closure}}
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\rt.rs:52
  21: std::panicking::try::do_call<closure-0,i32>
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:292
  22: panic_unwind::__rust_maybe_catch_panic
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libpanic_unwind\lib.rs:78
  23: std::panicking::try
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:270
  24: std::panic::catch_unwind
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panic.rs:394
  25: std::rt::lang_start_internal
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\rt.rs:51
  26: main
  27: invoke_main
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  28: __scrt_common_main_seh
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  29: BaseThreadInitThunk
  30: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by MaciejTest** [comment]
or 

atm single -n 'C:4,D:4,E:4,F:4,G:4,A:4,B:4,C:5' -t test.mid
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', src\libcore\result.rs:1188:5
stack backtrace:
   0:     0x7ff65ee4ed59 - backtrace::backtrace::trace_unsynchronized
                               at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
   1:     0x7ff65ee4ed59 - std::sys_common::backtrace::_print_fmt
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\sys_common\backtrace.rs:84
   2:     0x7ff65ee4ed59 - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\sys_common\backtrace.rs:61
   3:     0x7ff65ee65fbb - core::fmt::write
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libcore\fmt\mod.rs:1025
   4:     0x7ff65ee4ba84 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\io\mod.rs:1426
   5:     0x7ff65ee51699 - std::sys_common::backtrace::_print
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\sys_common\backtrace.rs:65
   6:     0x7ff65ee51699 - std::sys_common::backtrace::print
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\sys_common\backtrace.rs:50
   7:     0x7ff65ee51699 - std::panicking::default_hook::{{closure}}
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:193
   8:     0x7ff65ee512ec - std::panicking::default_hook
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:210
   9:     0x7ff65ee51e3c - std::panicking::rust_panic_with_hook
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:471
  10:     0x7ff65ee519c0 - std::panicking::begin_panic_handler
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:375
  11:     0x7ff65ee620fd - core::panicking::panic_fmt
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libcore\panicking.rs:84
  12:     0x7ff65ee621ff - core::result::unwrap_failed
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libcore\result.rs:1188
  13:     0x7ff65ede5bbd - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter::h7a8135aa97704d67
  14:     0x7ff65ede373d - <libatm::MIDINoteSequence as core::str::FromStr>::from_str::hb51bea5b3e58c615
  15:     0x7ff65edc96e2 - atm::directives::parse_sequence_argument::h3b666624bee7d8da
  16:     0x7ff65edc97b4 - <atm::directives::SingleDirectiveArgs as core::convert::From<&clap::args::arg_matches::ArgMatches>>::from::h4c545371192bf7d3
  17:     0x7ff65edc3e80 - atm::cli::Cli::run::h7b3c1f17f3e5cce8
  18:     0x7ff65edc103d - core::ptr::real_drop_in_place::h158ddf9daeaa1c50
  19:     0x7ff65edc1006 - vtable
  20:     0x7ff65ee51817 - std::rt::lang_start_internal::{{closure}}
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\rt.rs:52
  21:     0x7ff65ee51817 - std::panicking::try::do_call<closure-0,i32>
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:292
  22:     0x7ff65ee556d2 - panic_unwind::__rust_maybe_catch_panic
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libpanic_unwind\lib.rs:78
  23:     0x7ff65ee52062 - std::panicking::try
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panicking.rs:270
  24:     0x7ff65ee52062 - std::panic::catch_unwind
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\panic.rs:394
  25:     0x7ff65ee52062 - std::rt::lang_start_internal
                               at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8\/src\libstd\rt.rs:51
  26:     0x7ff65edc1077 - main
  27:     0x7ff65ee6da44 - invoke_main
                               at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  28:     0x7ff65ee6da44 - __scrt_common_main_seh
                               at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  29:     0x7ffddbc77bd4 - BaseThreadInitThunk
  30:     0x7ffddce4ced1 - RtlUserThreadStart

**Comment by allthemusicllc** [comment]
@MaciejTest are you running on a Windows machine? Is this possibly related to #14 or #15?

**Comment by eighthkeepa** [comment]
Hello. 
I got the same issue. Trying to run the tool on Debian Buster. 
It ends up like this all the time: 
```
./atm                 
thread 'main' panicked at 'Did not receive directive', src/cli.rs:133:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

```

I have to issues with compiling the tool though. I tried to compile with Rust from Debian repo and also with Rust, installed via rustup, as suggested on atm-cli github page.

**Comment by allthemusicllc** [comment]
@eighthkeepa that doesn't look like an error, you just need to specify a directive. Try running `./atm --help`. We are working on a new version that, amongst other things, will display a help menu when no CLI parameters/flags are provided. See #22.
