### ISSUE TITLE
Pre-built binaries

### ISSUE THREAD

**Issue by mkrl** [allthemusicllc/atm-cli#21]
It would be nice to have pre-built binaries ready to go.
For a general drive-by "try it out" it would've been amazing to have pre-built releases, even though it took less then a minute to compile.

I do understand this may be in its' early stage, perhaps that's something to consider for future development. You may also be able to run `cargo` and generate changelog and binaries with GitHub Actions.

The project itself is amazing, great job!

**Comment by allthemusicllc** [comment]
@mkrl thanks for the props! We would like to set up a simple CI/CD pipeline using GitHub Actions, but just aren't there yet. Hopefully within the next 4-6 months we will be, stay tuned!
