### ISSUE TITLE
Options to string multiple melodies into single MIDI file

### ISSUE THREAD

**Issue by jallwine** [allthemusicllc/atm-cli#24]
After watching your TED talk, I wanted a way to simply listen to a bunch of melodies strung together in a single MIDI file. With the [permissions issues](https://github.com/allthemusicllc/atm-cli/issues/16) and the way you compress multiple midi files it wasn't all that easy to simply play them. I decided to write my own [utilities](https://github.com/AllwineDesigns/atm-utilities) that allow a user to do the brute force generation, but store them in a single MIDI file rather than breaking each melody into a single file. It could be nice to see similar features added to atm-cli. My utilities are not very fleshed out with command line arguments, but hopefully they inspire something.

I understand that focus is placed on being able to store them efficiently, and it seems like batching several melodies into a single MIDI file could help with that. The headers in simplest MIDI file is 22 bytes. The track is 6x the number of notes plus 1 (assuming a running status of note on events is used for all notes). So in an 8 notes melody, 49 bytes. The header represents 30% of the file size. For a 12 note melody, the header would be 23% of the file size. If you string them together, the header could be negligible compared to the track size. Maybe compression handles this, but a more direct approach could be more accessible.

It seems like there could be a tangible way to store a minimal version of the melodies without needing to store the whole MIDI file as well (this is what the [generateNotes](https://github.com/AllwineDesigns/atm-utilities/blob/master/generateNotes.cpp) and [notes2Midi](https://github.com/AllwineDesigns/atm-utilities/blob/master/notes2Midi.cpp) commands do). Simply storing a single byte per note could save a lot of space and the conversion to a MIDI file is easy enough. Less than a byte per note could be achieved with the right approach. This seems comparable to using compression, but could be much more efficient if the right strategy is used.

Anyway, just some thoughts. Love the idea behind All The Music!

**Comment by allthemusicllc** [comment]
@jallwine thanks for you interest in the project! Addressing your comments:

1. Our initial use case required that we store every melody in separate MIDI files, and we still have that use case. However, you're not the first to ask for a different storage backend. We could support writing multiple melodies to the same, single track MIDI file if there's more interest in supporting it. We have fairly limited to work on the code and want to make sure we're implementing features that will be (relatively) widely used.
2. We have thought about implementing something similar (see: #8), which gets to the point of item 1: if enough users decide on an alternative storage backend that makes sense, we will look into implementing it!

**Comment by allthemusicllc** [comment]
@jallwine we're going to close this issue for now given the limited time we have to implement new features, though if you're interested in contributing, you could implement a new storage backend! Take a look at the [`StorageBackend`](https://github.com/allthemusicllc/atm-cli/blob/master/src/storage.rs#L28) trait. Based on your original comment, you might be interested in the `gen tar` or `gen tar-gz` directives. Those output formats are easier to work with.
