### ISSUE TITLE
Looking for cooperation

### ISSUE THREAD

**Issue by Dynamo-github** [allthemusicllc/atm-cli#30]
Dear author, I am a music lover and a software engineer.I have great interest in this project and hope to participate in it. I hope to get in touch with you and look forward to your reply ：）

**Comment by allthemusicllc** [comment]
@Dynamo-github thanks for reaching out! We're currently considering the future of this project and will likely be posting something in the next few months. We apologize for having gone radio silent for a while and appreciate the patience, this year has been difficult for everyone.  Stay safe and we'll be in touch here soon.
