### ISSUE TITLE
zsh: command not found: atm

### ISSUE THREAD

**Issue by ammccau** [allthemusicllc/atm-cli#35]
I've followed all the directions and cloned the repository today but continue to receive the 'zsh: command not found: atm' error.  I'm using a Macbook Pro running BigSur v11.1 (20C69). Any help will be much appreciated. I did see a similar issue posted and tried what was suggested, and that didn't work, either.

Thank you,

Anna

**Comment by ihatetoregister** [comment]
I just tested this and it seem to work on Big Sur. The error you get is that the command that this project is providing (atm) can't be found. Did you follow the build instructions?

```
$ git clone https://github.com/allthemusicllc/atm-cli.git
$ cd atm-cli
$ git submodule update --init
$ cargo build --release
$ cargo run --release -- -h # show usage
```

To run the atm command from command line you could either:
1. `$ cargo run --release -- -h`
2. `$ ./target/release/atm`
3. Install using: `$ cargo install --path .`. Then add cargo install dir to path: `$ export PATH=/Users/<yourname>/.cargo/bin:$PATH`. Then you should be able to run ´atm´ as any other command.

**Comment by ammccau** [comment]
Thank you! Solution #3 worked.

Anna
